// datos.ts
export const datos = {
    embarcaciones: [
        {

            matricula: 'EMB001',
            manga: 5.2,
            eslora: 15.8,
            origen: 'España',
            titular: 'Juan Pérez',
            imagen: 'url_imagen_1.jpg',
            numero_registro: 'REG001',
            datos_tecnicos: 'Especificaciones técnicas 1',
            modelo: 'Modelo A',
            nombre: 'Barco 1',
            tipo: 'Velero',
        },
        {

            matricula: 'EMB002',
            manga: 4.5,
            eslora: 12.3,
            origen: 'Italia',
            titular: 'Ana Rodríguez',
            imagen: 'url_imagen_2.jpg',
            numero_registro: 'REG002',
            datos_tecnicos: 'Especificaciones técnicas 2',
            modelo: 'Modelo B',
            nombre: 'Barco 2',
            tipo: 'Yate',
        },
        {

            matricula: 'EMB003',
            manga: 6.0,
            eslora: 18.5,
            origen: 'Grecia',
            titular: 'Pedro Martínez',
            imagen: 'url_imagen_3.jpg',
            numero_registro: 'REG003',
            datos_tecnicos: 'Especificaciones técnicas 3',
            modelo: 'Modelo C',
            nombre: 'Barco 3',
            tipo: 'Catamarán',
        },
        {

            matricula: 'EMB004',
            manga: 4.8,
            eslora: 14.2,
            origen: 'Francia',
            titular: 'Elena García',
            imagen: 'url_imagen_4.jpg',
            numero_registro: 'REG004',
            datos_tecnicos: 'Especificaciones técnicas 4',
            modelo: 'Modelo D',
            nombre: 'Barco 4',
            tipo: 'Lancha',
        },
        {

            matricula: 'EMB005',
            manga: 5.5,
            eslora: 16.7,
            origen: 'Portugal',
            titular: 'Luisa Sánchez',
            imagen: 'url_imagen_5.jpg',
            numero_registro: 'REG005',
            datos_tecnicos: 'Especificaciones técnicas 5',
            modelo: 'Modelo E',
            nombre: 'Barco 5',
            tipo: 'Velero',
        },
        {

            matricula: 'EMB006',
            manga: 6.2,
            eslora: 19.0,
            origen: 'Alemania',
            titular: 'Mario López',
            imagen: 'url_imagen_6.jpg',
            numero_registro: 'REG006',
            datos_tecnicos: 'Especificaciones técnicas 6',
            modelo: 'Modelo F',
            nombre: 'Barco 6',
            tipo: 'Yate',
        },
        {

            matricula: 'EMB007',
            manga: 5.0,
            eslora: 14.8,
            origen: 'Holanda',
            titular: 'Carmen Ruiz',
            imagen: 'url_imagen_7.jpg',
            numero_registro: 'REG007',
            datos_tecnicos: 'Especificaciones técnicas 7',
            modelo: 'Modelo G',
            nombre: 'Barco 7',
            tipo: 'Catamarán',
        },
        {

            matricula: 'EMB008',
            manga: 4.3,
            eslora: 11.5,
            origen: 'Suecia',
            titular: 'Javier García',
            imagen: 'url_imagen_8.jpg',
            numero_registro: 'REG008',
            datos_tecnicos: 'Especificaciones técnicas 8',
            modelo: 'Modelo H',
            nombre: 'Barco 8',
            tipo: 'Lancha',
        },
        {

            matricula: 'EMB009',
            manga: 5.8,
            eslora: 17.3,
            origen: 'Noruega',
            titular: 'Isabel Martínez',
            imagen: 'url_imagen_9.jpg',
            numero_registro: 'REG009',
            datos_tecnicos: 'Especificaciones técnicas 9',
            modelo: 'Modelo I',
            nombre: 'Barco 9',
            tipo: 'Velero',
        },
        {

            matricula: 'EMB010',
            manga: 6.5,
            eslora: 20.2,
            origen: 'Dinamarca',
            titular: 'Miguel Rodríguez',
            imagen: 'url_imagen_10.jpg',
            numero_registro: 'REG010',
            datos_tecnicos: 'Especificaciones técnicas 10',
            modelo: 'Modelo J',
            nombre: 'Barco 10',
            tipo: 'Yate',
        },
    ],
    tripulantes: [
        {

            numero_documento: 'DOC001',
            nombre: 'María López',
            sexo: 'Femenino',
            nacionalidad: 'Argentina',
        },
        {

            numero_documento: 'DOC002',
            nombre: 'Carlos González',
            sexo: 'Masculino',
            nacionalidad: 'Española',
        },
        {

            numero_documento: 'DOC003',
            nombre: 'Laura Pérez',
            sexo: 'Femenino',
            nacionalidad: 'Mexicana',
        },
        {

            numero_documento: 'DOC004',
            nombre: 'Alejandro Fernández',
            sexo: 'Masculino',
            nacionalidad: 'Chilena',
        },
        {

            numero_documento: 'DOC005',
            nombre: 'Sofía Martín',
            sexo: 'Femenino',
            nacionalidad: 'Colombiana',
        },
        {

            numero_documento: 'DOC006',
            nombre: 'Héctor Silva',
            sexo: 'Masculino',
            nacionalidad: 'Uruguaya',
        },
        {

            numero_documento: 'DOC007',
            nombre: 'Carolina Herrera',
            sexo: 'Femenino',
            nacionalidad: 'Venezolana',
        },
        {

            numero_documento: 'DOC008',
            nombre: 'Andrés Torres',
            sexo: 'Masculino',
            nacionalidad: 'Ecuatoriana',
        },
        {

            numero_documento: 'DOC009',
            nombre: 'Luisa García',
            sexo: 'Femenino',
            nacionalidad: 'Peruana',
        },
        {

            numero_documento: 'DOC010',
            nombre: 'Diego Morales',
            sexo: 'Masculino',
            nacionalidad: 'Boliviana',
        },
    ],
     roles : [
        {
          RolID: 1,
          NombreRol: "Concesionario",
          Permisos: "lectura,modificacion,eliminacion",
          Descripcion: "Rol con permisos de administrador",
        },
        {
          RolID: 2,
          NombreRol: "Guardamuelles",
          Permisos: "lectura,modificacion",
          Descripcion: "Rol para guardamuelles",
        },
        {
          RolID: 3,
          NombreRol: "Administrativo",
          Permisos: "lectura,modificacion",
          Descripcion: "Rol para editar y publicar contenido",
        },
        {
          RolID: 4,
          NombreRol: "Invitado",
          Permisos: "lectura",
          Descripcion: "Rol con permisos de solo lectura",
        },
        {
          RolID: 5,
          NombreRol: "Guardacivil",
          Permisos: "lectura,modificacion",
          Descripcion: "Rol con permisos de solo lectura",
        },
      ],
       usuarios: [
        {
          UsuarioID: 1,
          NombreCompleto: "Juan Pérez",
          NombreUsuario: "juanperez",
          Perfil: "Concesionario",
          Habilitado: true,
          InstalacionID: 1,
          DNI: "123456789",
          Contraseña: "hashed_password",
          Teléfono: "123-456-789",
          Email: "juan@example.com",
          Direccion: "Calle Principal 123",
          Imagen: "avatar_juan.png",
          Descripcion: "Usuario administrador principal",
          TipoUsuario: "concesionario",
        },
        {
          UsuarioID: 2,
          NombreCompleto: "María García",
          NombreUsuario: "mariag",
          Perfil: "Guardamuelles",
          Habilitado: true,
          InstalacionID: 1,
          DNI: "987654321",
          Contraseña: "hashed_password",
          Teléfono: "987-654-321",
          Email: "maria@example.com",
          Direccion: "Avenida Secundaria 456",
          Imagen: "avatar_maria.png",
          Descripcion: "Usuario guardamuelles del sistema",
          TipoUsuario: "Guardamuelles",
        },
        {
          UsuarioID: 3,
          NombreCompleto: "Carlos López",
          NombreUsuario: "carlosl",
          Perfil: "Invitado",
          Habilitado: true,
          InstalacionID: null,
          DNI: "456789123",
          Contraseña: "hashed_password",
          Teléfono: "456-789-123",
          Email: "carlos@example.com",
          Direccion: "Plaza Central 789",
          Imagen: "avatar_carlos.png",
          Descripcion: "Usuario invitador",
          TipoUsuario: "Invitado",
        },
        {
          UsuarioID: 4,
          NombreCompleto: "Laura Martínez",
          NombreUsuario: "lauram",
          Perfil: "Administrativo",
          Habilitado: true,
          InstalacionID: 1,
          DNI: "789123456",
          Contraseña: "hashed_password",
          Teléfono: "789-123-456",
          Email: "laura@example.com",
          Direccion: "Avenida Principal 987",
          Imagen: "avatar_laura.png",
          Descripcion: "Usuario administrativo",
          TipoUsuario: "Administrativo",
        },
        {
          UsuarioID: 5,
          NombreCompleto: "Pedro Rodríguez",
          NombreUsuario: "pedror",
          Perfil: "Guardacivil",
          Habilitado: true,
          InstalacionID: null,
          DNI: "321654987",
          Contraseña: "hashed_password",
          Teléfono: "321-654-987",
          Email: "pedro@example.com",
          Direccion: "Calle Secundaria 654",
          Imagen: "avatar_pedro.png",
          Descripcion: "Usuario de fuerzas de seguridad",
          TipoUsuario: "Guardacivil",
        },
      ],
      
    


};